- name: Install Docker on All Hosts
  hosts: coqnet
  remote_user: ubuntu
  become: yes # Run tasks with elevated privileges
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Update the cache if it's older than 1 hour

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Dockers official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update APT package index after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker Engine, CLI, and Containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is running and enabled at boot
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add the 'ubuntu' user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
        state: present
